### ISSUE TITLE
PetCharges Runtime Error When Calling Lizard Family Type Familiars

### ISSUE THREAD

**Issue by OggySMG** [rjtrenchard/PetCharges#1]
## Problem description

When running PetCharges version 1.9 and calling a familiar in the lizard family a runtime error occurs in the Windower console.  

> PetCharges: Lua runtime error: petcharges/mob_families.lua:157: attempt to concatenate field '?' (a nil value)

Tracing the error in the mob_families.lua it was discovered that a key/value pair for the lizard family is missing from the monster_species table.  Adding a key/value pair to this table and reloading PetCharges resolves the runtime error.

Example key/value pair:
` ["Lizard"] = "Lizard",`

### Steps to reproduce

1. Load PetCharges 1.9 addon
2. Call a familiar in the lizard family (i.e. Lizard Familiar / Jug Of Carrion Broth)

## System information

 * **FFXI Retail**: June 2024
 * **Windower Launcher version**: 4.3.7757.25903
 * **PetCharges**: 1.9

**Comment by rjtrenchard** [comment]
Hello! 
Thanks for the heads up, I amended the mob family table. This should be fixed now!
