### ISSUE TITLE
PetCharges Runtime Error When Calling Mayfly Familiar

### ISSUE THREAD

**Issue by OggySMG** [rjtrenchard/PetCharges#2]
## Problem description

When running PetCharges version 1.9.1 and calling the Mayfly familiar a runtime error occurs in the Windower console.  

> PetCharges: Lua runtime error: petcharges/mob_families.lua:157: attempt to concatenate field '?' (a nil value)

In the monster_species table within the mob_families.lua, the value for key "Fly" should be "Vermin" instead of "Insect". Changing this value and reloading PetCharges resolves the runtime error.

Example fixed key/value pair:
` ["Fly"] = "Vermin",`

### Steps to reproduce

1. Load PetCharges 1.9.1 addon
2. Call the Mayfly familiar (i.e. Jug Of Bug Broth)

## System information

 * **FFXI Retail**: June 2024
 * **Windower Launcher version**: 4.3.7757.25903
 * **PetCharges**: 1.9.1

**Comment by rjtrenchard** [comment]
Fixed, thank you!
